use_frameworks!

platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "12.0"
    end
  end
end

target 'DiStorage_Example' do
# https://cocoapods.org/pods/DiStorage
#    pod 'DiStorage', :path => '../'
#    pod 'DiStorage', :tag => '0.2.0', :git=> 'https://github.com/AlexeyYuPopkov/DiStorage_swift'
    pod 'DiStorage', '~> 0.2'
    pod 'MBProgressHUD'

    target 'DiStorage_Tests' do
        inherit! :search_paths
#        pod 'DiStorage', :path => '../', :testspecs => ['Tests']
#        pod 'DiStorage', :tag => '0.2.0', :git=> 'https://github.com/AlexeyYuPopkov/DiStorage_swift', :testspecs => ['Tests']
        pod 'DiStorage', '~> 0.2', :testspecs => ['Tests']
    end
    
    target 'DiStorage_UITests' do
        inherit! :search_paths
#        pod 'DiStorage', :path => '../'
#        pod 'DiStorage', :tag => '0.2.0', :git=> 'https://github.com/AlexeyYuPopkov/DiStorage_swift'
        pod 'DiStorage', '~> 0.2'
        pod 'MBProgressHUD'
    end
end
